version: '3'
services:
    flask:
        container_name: annotator_flask
        build:
            context: .
        ports:
            - '5000:5000'
        volumes:
            - './data/datasets:/data/datasets'
            - './flask:/workspace/flask'
        command: 'python3 /workspace/flask/run.py'
        depends_on:
            - database
    database:
        image: mongo:latest
        container_name: annotator_mongodb
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - './data/db:/data/db'
        ports:
            - '27017:27017'
        command: 'mongod --smallfiles --logpath=/dev/null'
